server:
  port: 40200

logging:
  config: classpath:log4j2-dev.yml

spring:
  profiles:
    include: info
  application:
    name: @project.artifactId@

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}-${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:40000/eureka
